---
title: "Texas County GDP"
author: "Shannon Carter"
date: "1/23/2020"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}

knitr::opts_chunk$set(echo = TRUE, warning = FALSE)
knitr::opts_knit$set(root.dir = "/Users/shannoncarter/Documents/JanuaryAdvisors/GDP_Counties")

```

### Prep Workspace

```{r prep workspace, warning = F, message = F}

## Set working directory and clear memory
setwd("/Users/shannoncarter/Documents/JanuaryAdvisors/GDP_Counties")
rm(list = ls(all = T))

## Load required packages
library(tidyverse)
library(tigris)
library(extrafont)
library(usmap)
library(maps)
library(magrittr)
library(leaflet)

## Load data
gdp_total <- read.csv("TXCounty_GDP.csv", header = T)
gdp_industry <- read.csv("gdp_industry_clean.csv", header = T)

## Plotting style elements
mytheme <- theme_bw(base_size = 15, base_family = "Franklin Gothic Medium") +
  theme(legend.text = element_text(size = 10),
        legend.title = element_text(size = 11),
        text = element_text(size = 14),     
        axis.title = element_text(size = 12),
        axis.text  = element_text(size = 8, family = "Consolas"),
        panel.grid = element_blank())

#options(tigris_class = 'sf', tigris_)
```

### Clean TX county GDP summaries

```{r}
# trim to raw gdp only
gdp_tot <- gdp_total[,1:5]

# gather by year
gdp_tot_long <- gather(gdp_tot, key = "year", value = "gdp", -county)
gdp_tot_long <- separate(gdp_tot_long, year, into = c(NA, "year"), sep = "_")

# change data types
gdp_tot_long$year <- as.numeric(gdp_tot_long$year)
gdp_tot_long$gdp <- gsub(",", "", gdp_tot_long$gdp)
gdp_tot_long$gdp <- as.numeric(gdp_tot_long$gdp)

```


### GDP time series by county

```{r}
ggplot(gdp_tot_long, aes(x = year, y = gdp, color = county)) + mytheme +
  geom_point() +
  geom_line() +
  theme(legend.position = "none")
```

### Delta GDP by county

```{r}
# add a delta gdp column
tx_gdp_delta <- gdp_tot_long %>% 
  filter(year != 2016 & year != 2017) %>% 
  spread(year, gdp)

tx_gdp_delta$delta_gdp <- (tx_gdp_delta[,3] - tx_gdp_delta[,2])/(tx_gdp_delta[,2])

ggplot(tx_gdp_delta, aes(x = reorder(county, delta_gdp), y = delta_gdp)) +
  geom_point(color = 'orange') +
  geom_hline(yintercept = 0, color = 'lightgray', linetype = 2) +
  mytheme +
  theme(axis.text.x = element_text(angle = 90, hjust = 1, vjust = 0)) +
  labs(x = "county",
       y = "%ΔGDP",
       title = "Proportional change in GDP from 2015-2018 for TX counties")
```

### Clean TX county GDP by industry

```{r}
# Remove all rows containing "addendum"
gdp_industry[!grepl("addendum", gdp_industry$Description),]

# Make all missing values NA
gdp_ind <- gdp_industry %>% 
  dplyr::na_if("(NA)") %>% 
  dplyr::na_if("(D)")

# Trim ", TX" out of county name
gdp_ind <- separate(gdp_ind, "county", into = c("county", NA), sep = ",")

# Select only private industries and give shorthand name for each
gdp_ind <- gdp_ind %>% 
  filter(industry_code %in% c(3, 6, 10:12, 34:36, 45, 50, 59, 68, 75, 82)) %>% 
  mutate(industry_short = case_when(
    industry_code == 3  ~ "agriculture",
    industry_code == 6  ~ 'mining',
    industry_code == 10 ~ 'utilities',
    industry_code == 11 ~ 'construction',
    industry_code == 12 ~ 'manufacturing',
    industry_code == 34 ~ 'wholesale',
    industry_code == 35 ~ 'retail',
    industry_code == 36 ~ 'transportation',
    industry_code == 45 ~ 'information',
    industry_code == 50 ~ 'finance_etc',
    industry_code == 59 ~ 'business_servs',
    industry_code == 68 ~ 'education',
    industry_code == 75 ~ 'arts',
    industry_code == 82 ~ 'other'))

# Gather by year
gdp_ind_long <- gather(gdp_ind, key = "year", value = "gdp", -c(county, industry_code, industry, industry_short))
gdp_ind_long <- separate(gdp_ind_long, year, into = c(NA, "year"), sep = "Y")

```


### Mapping 2018 GDP by county and industry

```{r}

# Trim data to county, industry, GDP, filter to 2018
gdp_leaf <- select(gdp_ind, 
             county = county,
             industry = industry_short,
             gdp = Y2018)
gdp_leaf$gdp <- as.numeric(gdp_leaf$gdp)
gdp_leaf <- spread(gdp_leaf, industry, gdp)
gdp_leaf <- filter(gdp_leaf, county != "Texas")

# Get shape files for TX counties from tigris
shape <- counties("Texas", cb = T)

# Join to shape file to df
df <- geo_join(shape, gdp_leaf, "NAME", "county")

# adding data to fill
palette <- colorBin("Reds", bins = 5, domain = df$arts, na.color = "#f0f9e8")

leaflet() %>% 
  addProviderTiles("CartoDB.Positron") %>% 
  setView(-99.9, 31.97, zoom = 5) %>% 
  addPolygons(
    data = df,
    color = 'white',
    weight = 1,
    fillColor = palette(df$arts),
    fillOpacity = 0.7,
    popup = paste0(df$county, "</br>", "GDP:", df$arts)) %>% 
  addProviderTiles(df$education, group = "Education")
```

```{r}

plot_usmap(regions = "counties", include = "TX") + 
  labs(title = "TX Counties",
       subtitle = "This is a blank map of the counties of Texas.") + 
  theme(panel.background = element_rect(color = "black", fill = "lightblue"))

tx_counties <- usmap::us_map(regions = "counties", include = "TX")
tx_counties <- separate(tx_counties, county, into = c("county", NA), sep = " ")
```

```{r}
# join county data with gdp data
tx_gdp_county <- left_join(tx_gdp_delta, tx_counties, by = 'county')
```

```{r}

plot_usmap(data = tx_gdp_county, values = "delta_gdp") + 
  scale_fill_continuous() + 
  theme(legend.position = "right")
```
```{r}
leaflet(options = leafletOptions(minZoom = 0, maxZoom = 18))
mapStates = maps::map("state", fill = TRUE, plot = FALSE)
basic <- leaflet(data = mapStates) %>% 
  addTiles() %>%
  addPolygons(fillColor = topo.colors(10, alpha = NULL), stroke = FALSE)
```
```{r}
m = leaflet() %>% addTiles()
df = data.frame(
  lat = rnorm(100),
  lng = rnorm(100),
  size = runif(100, 5, 20),
  color = sample(colors(), 100)
)
m = leaflet(df) %>% addTiles()
m %>% addCircleMarkers(radius = ~size, color = ~color, fill = FALSE)
m %>% addCircleMarkers(radius = runif(100, 4, 10), color = c('red'))
```




